@startwbs wbs
* Factory Production Line Project
** Project Management Plan (PMP)
*** Project scope (5W1H)
*** Project Objectives identification (SMART)
*** SWOT analysis
*** Feasibility assessment
*** Market analysis
*** Project planning
**** Work Breakdown Struture (WBS)
**** PERT network
**** Plan scheduling (GANTT)
*** Role and responsabilities
**** Organization Breakdown Structure (OBS)
**** Responsability assignment matrix (RACI matrix)
*** Risk management
*** Performance and results indicators
*** Resource management
*** Communication plan
*** PMP redaction

** PMP Validation
*** Presentation to Stakeholders
*** Security management
**** Security plan
**** Security plan Communication
**** Security equipment installation

** Design Phase
*** Engineering and technical specifications
*** Detailed architectural plans
*** 3D Modeling
*** Model validation

** Production Line
*** Raw materials and Equipement Purchase
*** Production line installation

** Project Closeout
*** Production line test and validation
*** Project documentation
*** Post-implementation sustainability review

** Operations and Maintenance
*** Development of operation manuals
*** Establishment of maintenance schedules
*** Training of personnel dedicated to maintenance
*** Continuous improvement programs for sustainability practices
@endwbs